name: Fridays Scheduled Update
on:
  pull_request:
#  schedule:
#    - cron: "0 10 * * 5" # // Every Friday at 10AM UTC

jobs:
  update-create-pr:
    name: "Update Data and Create PR"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: |
          sudo apt-get install -y jq zsh
          npm install
          git config --global user.email "${{ secrets.GIT_COMMIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_COMMIT_AUTHOR }}"

      - name: Upgrade data sources and regenerate dist files
        run: |
          npm upgrade pokemon-showdown
          make build

          if [[ `git status --porcelain ./dist` ]]; then
            # Changes
            NEW_TAG=$(date +'%Y.%m.%d')
            NEW_BRANCH="update-${NEW_TAG}"

            git checkout -b "${NEW_BRANCH}"
            git add -A
            git commit -m "Changes from ${NEW_TAG}"
            git push --set-upstream origin "${NEW_BRANCH}"
            git push
            sleep 1

            curl --request POST \
              --url "${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/pulls" \
              --header "Accept: application/vnd.github.v3+json" \
              --header 'authorization: token ${{ secrets.GITHUB_TOKEN }}' \
              --data "{\"head\":\"${NEW_BRANCH}\",\"base\":\"main\",\"title\":\"${NEW_BRANCH}\"}"
          else
            echo "There are no changes. Nothing to commit."
          fi
